// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: app_presence.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Announces a third-party app active on a node, reverse-DNS style app_id
// (e.g. net.quakemesh.privatechat) to avoid collisions without a registry.
type AppPresenceRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AppId              string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName            string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppVersion         string                 `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	LastReportedUnixMs int64                  `protobuf:"varint,5,opt,name=last_reported_unix_ms,json=lastReportedUnixMs,proto3" json:"last_reported_unix_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AppPresenceRecord) Reset() {
	*x = AppPresenceRecord{}
	mi := &file_app_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppPresenceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPresenceRecord) ProtoMessage() {}

func (x *AppPresenceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_app_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPresenceRecord.ProtoReflect.Descriptor instead.
func (*AppPresenceRecord) Descriptor() ([]byte, []int) {
	return file_app_presence_proto_rawDescGZIP(), []int{0}
}

func (x *AppPresenceRecord) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *AppPresenceRecord) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppPresenceRecord) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppPresenceRecord) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *AppPresenceRecord) GetLastReportedUnixMs() int64 {
	if x != nil {
		return x.LastReportedUnixMs
	}
	return 0
}

var File_app_presence_proto protoreflect.FileDescriptor

const file_app_presence_proto_rawDesc = "" +
	"\n" +
	"\x12app_presence.proto\x12\x0equakemesh.wire\"\xb2\x01\n" +
	"\x11AppPresenceRecord\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x1f\n" +
	"\vapp_version\x18\x04 \x01(\tR\n" +
	"appVersion\x121\n" +
	"\x15last_reported_unix_ms\x18\x05 \x01(\x03R\x12lastReportedUnixMsBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_app_presence_proto_rawDescOnce sync.Once
	file_app_presence_proto_rawDescData []byte
)

func file_app_presence_proto_rawDescGZIP() []byte {
	file_app_presence_proto_rawDescOnce.Do(func() {
		file_app_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_presence_proto_rawDesc), len(file_app_presence_proto_rawDesc)))
	})
	return file_app_presence_proto_rawDescData
}

var file_app_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_presence_proto_goTypes = []any{
	(*AppPresenceRecord)(nil), // 0: quakemesh.wire.AppPresenceRecord
}
var file_app_presence_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_presence_proto_init() }
func file_app_presence_proto_init() {
	if File_app_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_presence_proto_rawDesc), len(file_app_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_presence_proto_goTypes,
		DependencyIndexes: file_app_presence_proto_depIdxs,
		MessageInfos:      file_app_presence_proto_msgTypes,
	}.Build()
	File_app_presence_proto = out.File
	file_app_presence_proto_goTypes = nil
	file_app_presence_proto_depIdxs = nil
}
