// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ban_list.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A ban proposal is never auto-enforced -- every hub admin explicitly
// Agrees or Disagrees, and both the proposal and every verdict are
// gossiped so the network can see how many hubs enforced it.
type BanProposal struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BanId            []byte                 `protobuf:"bytes,1,opt,name=ban_id,json=banId,proto3" json:"ban_id,omitempty"`
	AppId            string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionRange     string                 `protobuf:"bytes,3,opt,name=version_range,json=versionRange,proto3" json:"version_range,omitempty"`
	Reason           string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ProposedByHubId  []byte                 `protobuf:"bytes,5,opt,name=proposed_by_hub_id,json=proposedByHubId,proto3" json:"proposed_by_hub_id,omitempty"`
	ProposedAtUnixMs int64                  `protobuf:"varint,6,opt,name=proposed_at_unix_ms,json=proposedAtUnixMs,proto3" json:"proposed_at_unix_ms,omitempty"`
	Signature        []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BanProposal) Reset() {
	*x = BanProposal{}
	mi := &file_ban_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanProposal) ProtoMessage() {}

func (x *BanProposal) ProtoReflect() protoreflect.Message {
	mi := &file_ban_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanProposal.ProtoReflect.Descriptor instead.
func (*BanProposal) Descriptor() ([]byte, []int) {
	return file_ban_list_proto_rawDescGZIP(), []int{0}
}

func (x *BanProposal) GetBanId() []byte {
	if x != nil {
		return x.BanId
	}
	return nil
}

func (x *BanProposal) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BanProposal) GetVersionRange() string {
	if x != nil {
		return x.VersionRange
	}
	return ""
}

func (x *BanProposal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanProposal) GetProposedByHubId() []byte {
	if x != nil {
		return x.ProposedByHubId
	}
	return nil
}

func (x *BanProposal) GetProposedAtUnixMs() int64 {
	if x != nil {
		return x.ProposedAtUnixMs
	}
	return 0
}

func (x *BanProposal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type BanVerdict struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BanId           []byte                 `protobuf:"bytes,1,opt,name=ban_id,json=banId,proto3" json:"ban_id,omitempty"`
	HubId           []byte                 `protobuf:"bytes,2,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Agree           bool                   `protobuf:"varint,3,opt,name=agree,proto3" json:"agree,omitempty"`
	DecidedAtUnixMs int64                  `protobuf:"varint,4,opt,name=decided_at_unix_ms,json=decidedAtUnixMs,proto3" json:"decided_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BanVerdict) Reset() {
	*x = BanVerdict{}
	mi := &file_ban_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanVerdict) ProtoMessage() {}

func (x *BanVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_ban_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanVerdict.ProtoReflect.Descriptor instead.
func (*BanVerdict) Descriptor() ([]byte, []int) {
	return file_ban_list_proto_rawDescGZIP(), []int{1}
}

func (x *BanVerdict) GetBanId() []byte {
	if x != nil {
		return x.BanId
	}
	return nil
}

func (x *BanVerdict) GetHubId() []byte {
	if x != nil {
		return x.HubId
	}
	return nil
}

func (x *BanVerdict) GetAgree() bool {
	if x != nil {
		return x.Agree
	}
	return false
}

func (x *BanVerdict) GetDecidedAtUnixMs() int64 {
	if x != nil {
		return x.DecidedAtUnixMs
	}
	return 0
}

var File_ban_list_proto protoreflect.FileDescriptor

const file_ban_list_proto_rawDesc = "" +
	"\n" +
	"\x0eban_list.proto\x12\x0equakemesh.wire\"\xf2\x01\n" +
	"\vBanProposal\x12\x15\n" +
	"\x06ban_id\x18\x01 \x01(\fR\x05banId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12#\n" +
	"\rversion_range\x18\x03 \x01(\tR\fversionRange\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12+\n" +
	"\x12proposed_by_hub_id\x18\x05 \x01(\fR\x0fproposedByHubId\x12-\n" +
	"\x13proposed_at_unix_ms\x18\x06 \x01(\x03R\x10proposedAtUnixMs\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"}\n" +
	"\n" +
	"BanVerdict\x12\x15\n" +
	"\x06ban_id\x18\x01 \x01(\fR\x05banId\x12\x15\n" +
	"\x06hub_id\x18\x02 \x01(\fR\x05hubId\x12\x14\n" +
	"\x05agree\x18\x03 \x01(\bR\x05agree\x12+\n" +
	"\x12decided_at_unix_ms\x18\x04 \x01(\x03R\x0fdecidedAtUnixMsBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_ban_list_proto_rawDescOnce sync.Once
	file_ban_list_proto_rawDescData []byte
)

func file_ban_list_proto_rawDescGZIP() []byte {
	file_ban_list_proto_rawDescOnce.Do(func() {
		file_ban_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ban_list_proto_rawDesc), len(file_ban_list_proto_rawDesc)))
	})
	return file_ban_list_proto_rawDescData
}

var file_ban_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ban_list_proto_goTypes = []any{
	(*BanProposal)(nil), // 0: quakemesh.wire.BanProposal
	(*BanVerdict)(nil),  // 1: quakemesh.wire.BanVerdict
}
var file_ban_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ban_list_proto_init() }
func file_ban_list_proto_init() {
	if File_ban_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ban_list_proto_rawDesc), len(file_ban_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ban_list_proto_goTypes,
		DependencyIndexes: file_ban_list_proto_depIdxs,
		MessageInfos:      file_ban_list_proto_msgTypes,
	}.Build()
	File_ban_list_proto = out.File
	file_ban_list_proto_goTypes = nil
	file_ban_list_proto_depIdxs = nil
}
