// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: dtn.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Store-and-forward bundle, following the store-carry-forward model
// (Bundle Protocol / RFC 9171). Persisted in the dtq_queue SQLite table
// until a route appears or it expires.
type DtnBundle struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BundleId        []byte                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	SrcNodeId       []byte                 `protobuf:"bytes,2,opt,name=src_node_id,json=srcNodeId,proto3" json:"src_node_id,omitempty"`
	DstNodeId       []byte                 `protobuf:"bytes,3,opt,name=dst_node_id,json=dstNodeId,proto3" json:"dst_node_id,omitempty"`
	Payload         []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,5,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	RetryCount      uint32                 `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DtnBundle) Reset() {
	*x = DtnBundle{}
	mi := &file_dtn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtnBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtnBundle) ProtoMessage() {}

func (x *DtnBundle) ProtoReflect() protoreflect.Message {
	mi := &file_dtn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtnBundle.ProtoReflect.Descriptor instead.
func (*DtnBundle) Descriptor() ([]byte, []int) {
	return file_dtn_proto_rawDescGZIP(), []int{0}
}

func (x *DtnBundle) GetBundleId() []byte {
	if x != nil {
		return x.BundleId
	}
	return nil
}

func (x *DtnBundle) GetSrcNodeId() []byte {
	if x != nil {
		return x.SrcNodeId
	}
	return nil
}

func (x *DtnBundle) GetDstNodeId() []byte {
	if x != nil {
		return x.DstNodeId
	}
	return nil
}

func (x *DtnBundle) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DtnBundle) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *DtnBundle) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_dtn_proto protoreflect.FileDescriptor

const file_dtn_proto_rawDesc = "" +
	"\n" +
	"\tdtn.proto\x12\x0equakemesh.wire\"\xd0\x01\n" +
	"\tDtnBundle\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\fR\bbundleId\x12\x1e\n" +
	"\vsrc_node_id\x18\x02 \x01(\fR\tsrcNodeId\x12\x1e\n" +
	"\vdst_node_id\x18\x03 \x01(\fR\tdstNodeId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12+\n" +
	"\x12expires_at_unix_ms\x18\x05 \x01(\x03R\x0fexpiresAtUnixMs\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\rR\n" +
	"retryCountBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_dtn_proto_rawDescOnce sync.Once
	file_dtn_proto_rawDescData []byte
)

func file_dtn_proto_rawDescGZIP() []byte {
	file_dtn_proto_rawDescOnce.Do(func() {
		file_dtn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtn_proto_rawDesc), len(file_dtn_proto_rawDesc)))
	})
	return file_dtn_proto_rawDescData
}

var file_dtn_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dtn_proto_goTypes = []any{
	(*DtnBundle)(nil), // 0: quakemesh.wire.DtnBundle
}
var file_dtn_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dtn_proto_init() }
func file_dtn_proto_init() {
	if File_dtn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtn_proto_rawDesc), len(file_dtn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtn_proto_goTypes,
		DependencyIndexes: file_dtn_proto_depIdxs,
		MessageInfos:      file_dtn_proto_msgTypes,
	}.Build()
	File_dtn_proto = out.File
	file_dtn_proto_goTypes = nil
	file_dtn_proto_depIdxs = nil
}
