// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: frame.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame is the outermost envelope for every message sent over any transport.
// Intermediate repeater nodes read only this header; the payload is opaque
// ciphertext sealed to dst_node_id.
type Frame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SrcNodeId      []byte                 `protobuf:"bytes,1,opt,name=src_node_id,json=srcNodeId,proto3" json:"src_node_id,omitempty"`
	DstNodeId      []byte                 `protobuf:"bytes,2,opt,name=dst_node_id,json=dstNodeId,proto3" json:"dst_node_id,omitempty"`
	HopCount       uint32                 `protobuf:"varint,3,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	Ttl            uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	TransportHints []string               `protobuf:"bytes,5,rep,name=transport_hints,json=transportHints,proto3" json:"transport_hints,omitempty"`
	Payload        []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetSrcNodeId() []byte {
	if x != nil {
		return x.SrcNodeId
	}
	return nil
}

func (x *Frame) GetDstNodeId() []byte {
	if x != nil {
		return x.DstNodeId
	}
	return nil
}

func (x *Frame) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *Frame) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Frame) GetTransportHints() []string {
	if x != nil {
		return x.TransportHints
	}
	return nil
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_frame_proto protoreflect.FileDescriptor

const file_frame_proto_rawDesc = "" +
	"\n" +
	"\vframe.proto\x12\x0equakemesh.wire\"\xb9\x01\n" +
	"\x05Frame\x12\x1e\n" +
	"\vsrc_node_id\x18\x01 \x01(\fR\tsrcNodeId\x12\x1e\n" +
	"\vdst_node_id\x18\x02 \x01(\fR\tdstNodeId\x12\x1b\n" +
	"\thop_count\x18\x03 \x01(\rR\bhopCount\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12'\n" +
	"\x0ftransport_hints\x18\x05 \x03(\tR\x0etransportHints\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayloadBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_frame_proto_rawDescOnce sync.Once
	file_frame_proto_rawDescData []byte
)

func file_frame_proto_rawDescGZIP() []byte {
	file_frame_proto_rawDescOnce.Do(func() {
		file_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frame_proto_rawDesc), len(file_frame_proto_rawDesc)))
	})
	return file_frame_proto_rawDescData
}

var file_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frame_proto_goTypes = []any{
	(*Frame)(nil), // 0: quakemesh.wire.Frame
}
var file_frame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frame_proto_init() }
func file_frame_proto_init() {
	if File_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frame_proto_rawDesc), len(file_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frame_proto_goTypes,
		DependencyIndexes: file_frame_proto_depIdxs,
		MessageInfos:      file_frame_proto_msgTypes,
	}.Build()
	File_frame_proto = out.File
	file_frame_proto_goTypes = nil
	file_frame_proto_depIdxs = nil
}
