// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: hub_sync.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gossiped node registry record. Records merge last-writer-wins by
// timestamp; self-attested fields carry the node's own signature and
// hub-observed fields are attributed to the observing hub.
type NodeRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FirstSeenUnixMs int64                  `protobuf:"varint,2,opt,name=first_seen_unix_ms,json=firstSeenUnixMs,proto3" json:"first_seen_unix_ms,omitempty"`
	LastSeenUnixMs  int64                  `protobuf:"varint,3,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	LastLat         float64                `protobuf:"fixed64,4,opt,name=last_lat,json=lastLat,proto3" json:"last_lat,omitempty"`
	LastLon         float64                `protobuf:"fixed64,5,opt,name=last_lon,json=lastLon,proto3" json:"last_lon,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TrustScore      int32                  `protobuf:"varint,7,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeRecord) Reset() {
	*x = NodeRecord{}
	mi := &file_hub_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRecord) ProtoMessage() {}

func (x *NodeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_hub_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRecord.ProtoReflect.Descriptor instead.
func (*NodeRecord) Descriptor() ([]byte, []int) {
	return file_hub_sync_proto_rawDescGZIP(), []int{0}
}

func (x *NodeRecord) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *NodeRecord) GetFirstSeenUnixMs() int64 {
	if x != nil {
		return x.FirstSeenUnixMs
	}
	return 0
}

func (x *NodeRecord) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

func (x *NodeRecord) GetLastLat() float64 {
	if x != nil {
		return x.LastLat
	}
	return 0
}

func (x *NodeRecord) GetLastLon() float64 {
	if x != nil {
		return x.LastLon
	}
	return 0
}

func (x *NodeRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeRecord) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

// One Hub-to-Hub gossip exchange payload.
type HubSyncMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromHubId     []byte                 `protobuf:"bytes,1,opt,name=from_hub_id,json=fromHubId,proto3" json:"from_hub_id,omitempty"`
	NodeRecords   []*NodeRecord          `protobuf:"bytes,2,rep,name=node_records,json=nodeRecords,proto3" json:"node_records,omitempty"`
	RelayHubs     []*RelayHubRecord      `protobuf:"bytes,3,rep,name=relay_hubs,json=relayHubs,proto3" json:"relay_hubs,omitempty"`
	AppPresence   []*AppPresenceRecord   `protobuf:"bytes,4,rep,name=app_presence,json=appPresence,proto3" json:"app_presence,omitempty"`
	BanProposals  []*BanProposal         `protobuf:"bytes,5,rep,name=ban_proposals,json=banProposals,proto3" json:"ban_proposals,omitempty"`
	BanVerdicts   []*BanVerdict          `protobuf:"bytes,6,rep,name=ban_verdicts,json=banVerdicts,proto3" json:"ban_verdicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubSyncMessage) Reset() {
	*x = HubSyncMessage{}
	mi := &file_hub_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubSyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubSyncMessage) ProtoMessage() {}

func (x *HubSyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hub_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubSyncMessage.ProtoReflect.Descriptor instead.
func (*HubSyncMessage) Descriptor() ([]byte, []int) {
	return file_hub_sync_proto_rawDescGZIP(), []int{1}
}

func (x *HubSyncMessage) GetFromHubId() []byte {
	if x != nil {
		return x.FromHubId
	}
	return nil
}

func (x *HubSyncMessage) GetNodeRecords() []*NodeRecord {
	if x != nil {
		return x.NodeRecords
	}
	return nil
}

func (x *HubSyncMessage) GetRelayHubs() []*RelayHubRecord {
	if x != nil {
		return x.RelayHubs
	}
	return nil
}

func (x *HubSyncMessage) GetAppPresence() []*AppPresenceRecord {
	if x != nil {
		return x.AppPresence
	}
	return nil
}

func (x *HubSyncMessage) GetBanProposals() []*BanProposal {
	if x != nil {
		return x.BanProposals
	}
	return nil
}

func (x *HubSyncMessage) GetBanVerdicts() []*BanVerdict {
	if x != nil {
		return x.BanVerdicts
	}
	return nil
}

var File_hub_sync_proto protoreflect.FileDescriptor

const file_hub_sync_proto_rawDesc = "" +
	"\n" +
	"\x0ehub_sync.proto\x12\x0equakemesh.wire\x1a\x0frelay_hub.proto\x1a\x0eban_list.proto\x1a\x12app_presence.proto\"\xec\x01\n" +
	"\n" +
	"NodeRecord\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12+\n" +
	"\x12first_seen_unix_ms\x18\x02 \x01(\x03R\x0ffirstSeenUnixMs\x12)\n" +
	"\x11last_seen_unix_ms\x18\x03 \x01(\x03R\x0elastSeenUnixMs\x12\x19\n" +
	"\blast_lat\x18\x04 \x01(\x01R\alastLat\x12\x19\n" +
	"\blast_lon\x18\x05 \x01(\x01R\alastLon\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vtrust_score\x18\a \x01(\x05R\n" +
	"trustScore\"\xf5\x02\n" +
	"\x0eHubSyncMessage\x12\x1e\n" +
	"\vfrom_hub_id\x18\x01 \x01(\fR\tfromHubId\x12=\n" +
	"\fnode_records\x18\x02 \x03(\v2\x1a.quakemesh.wire.NodeRecordR\vnodeRecords\x12=\n" +
	"\n" +
	"relay_hubs\x18\x03 \x03(\v2\x1e.quakemesh.wire.RelayHubRecordR\trelayHubs\x12D\n" +
	"\fapp_presence\x18\x04 \x03(\v2!.quakemesh.wire.AppPresenceRecordR\vappPresence\x12@\n" +
	"\rban_proposals\x18\x05 \x03(\v2\x1b.quakemesh.wire.BanProposalR\fbanProposals\x12=\n" +
	"\fban_verdicts\x18\x06 \x03(\v2\x1a.quakemesh.wire.BanVerdictR\vbanVerdictsBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_hub_sync_proto_rawDescOnce sync.Once
	file_hub_sync_proto_rawDescData []byte
)

func file_hub_sync_proto_rawDescGZIP() []byte {
	file_hub_sync_proto_rawDescOnce.Do(func() {
		file_hub_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_sync_proto_rawDesc), len(file_hub_sync_proto_rawDesc)))
	})
	return file_hub_sync_proto_rawDescData
}

var file_hub_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hub_sync_proto_goTypes = []any{
	(*NodeRecord)(nil),        // 0: quakemesh.wire.NodeRecord
	(*HubSyncMessage)(nil),    // 1: quakemesh.wire.HubSyncMessage
	(*RelayHubRecord)(nil),    // 2: quakemesh.wire.RelayHubRecord
	(*AppPresenceRecord)(nil), // 3: quakemesh.wire.AppPresenceRecord
	(*BanProposal)(nil),       // 4: quakemesh.wire.BanProposal
	(*BanVerdict)(nil),        // 5: quakemesh.wire.BanVerdict
}
var file_hub_sync_proto_depIdxs = []int32{
	0, // 0: quakemesh.wire.HubSyncMessage.node_records:type_name -> quakemesh.wire.NodeRecord
	2, // 1: quakemesh.wire.HubSyncMessage.relay_hubs:type_name -> quakemesh.wire.RelayHubRecord
	3, // 2: quakemesh.wire.HubSyncMessage.app_presence:type_name -> quakemesh.wire.AppPresenceRecord
	4, // 3: quakemesh.wire.HubSyncMessage.ban_proposals:type_name -> quakemesh.wire.BanProposal
	5, // 4: quakemesh.wire.HubSyncMessage.ban_verdicts:type_name -> quakemesh.wire.BanVerdict
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hub_sync_proto_init() }
func file_hub_sync_proto_init() {
	if File_hub_sync_proto != nil {
		return
	}
	file_relay_hub_proto_init()
	file_ban_list_proto_init()
	file_app_presence_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_sync_proto_rawDesc), len(file_hub_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hub_sync_proto_goTypes,
		DependencyIndexes: file_hub_sync_proto_depIdxs,
		MessageInfos:      file_hub_sync_proto_msgTypes,
	}.Build()
	File_hub_sync_proto = out.File
	file_hub_sync_proto_goTypes = nil
	file_hub_sync_proto_depIdxs = nil
}
