// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: management.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Live event stream from a Hub's loopback management API (127.0.0.1:8083)
// to QuakeMeshMonitor, delivered over the Monitor's /ws WebSocket endpoint.
type ManagementEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EmittedAtUnixMs int64                  `protobuf:"varint,1,opt,name=emitted_at_unix_ms,json=emittedAtUnixMs,proto3" json:"emitted_at_unix_ms,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ManagementEvent_NodeStatusChanged
	//	*ManagementEvent_RouteChanged
	//	*ManagementEvent_DtnQueueDepthChanged
	//	*ManagementEvent_HubStatusChanged
	//	*ManagementEvent_InternetFallbackChanged
	Event         isManagementEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagementEvent) Reset() {
	*x = ManagementEvent{}
	mi := &file_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementEvent) ProtoMessage() {}

func (x *ManagementEvent) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementEvent.ProtoReflect.Descriptor instead.
func (*ManagementEvent) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

func (x *ManagementEvent) GetEmittedAtUnixMs() int64 {
	if x != nil {
		return x.EmittedAtUnixMs
	}
	return 0
}

func (x *ManagementEvent) GetEvent() isManagementEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ManagementEvent) GetNodeStatusChanged() *NodeStatusChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_NodeStatusChanged); ok {
			return x.NodeStatusChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetRouteChanged() *RouteChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_RouteChanged); ok {
			return x.RouteChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetDtnQueueDepthChanged() *DtnQueueDepthChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_DtnQueueDepthChanged); ok {
			return x.DtnQueueDepthChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetHubStatusChanged() *HubStatusChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_HubStatusChanged); ok {
			return x.HubStatusChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetInternetFallbackChanged() *InternetFallbackChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_InternetFallbackChanged); ok {
			return x.InternetFallbackChanged
		}
	}
	return nil
}

type isManagementEvent_Event interface {
	isManagementEvent_Event()
}

type ManagementEvent_NodeStatusChanged struct {
	NodeStatusChanged *NodeStatusChanged `protobuf:"bytes,2,opt,name=node_status_changed,json=nodeStatusChanged,proto3,oneof"`
}

type ManagementEvent_RouteChanged struct {
	RouteChanged *RouteChanged `protobuf:"bytes,3,opt,name=route_changed,json=routeChanged,proto3,oneof"`
}

type ManagementEvent_DtnQueueDepthChanged struct {
	DtnQueueDepthChanged *DtnQueueDepthChanged `protobuf:"bytes,4,opt,name=dtn_queue_depth_changed,json=dtnQueueDepthChanged,proto3,oneof"`
}

type ManagementEvent_HubStatusChanged struct {
	HubStatusChanged *HubStatusChanged `protobuf:"bytes,5,opt,name=hub_status_changed,json=hubStatusChanged,proto3,oneof"`
}

type ManagementEvent_InternetFallbackChanged struct {
	InternetFallbackChanged *InternetFallbackChanged `protobuf:"bytes,6,opt,name=internet_fallback_changed,json=internetFallbackChanged,proto3,oneof"`
}

func (*ManagementEvent_NodeStatusChanged) isManagementEvent_Event() {}

func (*ManagementEvent_RouteChanged) isManagementEvent_Event() {}

func (*ManagementEvent_DtnQueueDepthChanged) isManagementEvent_Event() {}

func (*ManagementEvent_HubStatusChanged) isManagementEvent_Event() {}

func (*ManagementEvent_InternetFallbackChanged) isManagementEvent_Event() {}

type HubStatusChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HubId         []byte                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubStatusChanged) Reset() {
	*x = HubStatusChanged{}
	mi := &file_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubStatusChanged) ProtoMessage() {}

func (x *HubStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubStatusChanged.ProtoReflect.Descriptor instead.
func (*HubStatusChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{1}
}

func (x *HubStatusChanged) GetHubId() []byte {
	if x != nil {
		return x.HubId
	}
	return nil
}

func (x *HubStatusChanged) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NodeStatusChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusChanged) Reset() {
	*x = NodeStatusChanged{}
	mi := &file_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusChanged) ProtoMessage() {}

func (x *NodeStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusChanged.ProtoReflect.Descriptor instead.
func (*NodeStatusChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{2}
}

func (x *NodeStatusChanged) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *NodeStatusChanged) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RouteChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstNodeId     []byte                 `protobuf:"bytes,1,opt,name=dst_node_id,json=dstNodeId,proto3" json:"dst_node_id,omitempty"`
	NextHopNodeId []byte                 `protobuf:"bytes,2,opt,name=next_hop_node_id,json=nextHopNodeId,proto3" json:"next_hop_node_id,omitempty"`
	Tq            float64                `protobuf:"fixed64,3,opt,name=tq,proto3" json:"tq,omitempty"`
	HopCount      uint32                 `protobuf:"varint,4,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteChanged) Reset() {
	*x = RouteChanged{}
	mi := &file_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteChanged) ProtoMessage() {}

func (x *RouteChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteChanged.ProtoReflect.Descriptor instead.
func (*RouteChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{3}
}

func (x *RouteChanged) GetDstNodeId() []byte {
	if x != nil {
		return x.DstNodeId
	}
	return nil
}

func (x *RouteChanged) GetNextHopNodeId() []byte {
	if x != nil {
		return x.NextHopNodeId
	}
	return nil
}

func (x *RouteChanged) GetTq() float64 {
	if x != nil {
		return x.Tq
	}
	return 0
}

func (x *RouteChanged) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

type DtnQueueDepthChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depth         uint32                 `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtnQueueDepthChanged) Reset() {
	*x = DtnQueueDepthChanged{}
	mi := &file_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtnQueueDepthChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtnQueueDepthChanged) ProtoMessage() {}

func (x *DtnQueueDepthChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtnQueueDepthChanged.ProtoReflect.Descriptor instead.
func (*DtnQueueDepthChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{4}
}

func (x *DtnQueueDepthChanged) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type InternetFallbackChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternetFallbackChanged) Reset() {
	*x = InternetFallbackChanged{}
	mi := &file_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternetFallbackChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternetFallbackChanged) ProtoMessage() {}

func (x *InternetFallbackChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternetFallbackChanged.ProtoReflect.Descriptor instead.
func (*InternetFallbackChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{5}
}

func (x *InternetFallbackChanged) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_management_proto protoreflect.FileDescriptor

const file_management_proto_rawDesc = "" +
	"\n" +
	"\x10management.proto\x12\x0equakemesh.wire\"\xf9\x03\n" +
	"\x0fManagementEvent\x12+\n" +
	"\x12emitted_at_unix_ms\x18\x01 \x01(\x03R\x0femittedAtUnixMs\x12S\n" +
	"\x13node_status_changed\x18\x02 \x01(\v2!.quakemesh.wire.NodeStatusChangedH\x00R\x11nodeStatusChanged\x12C\n" +
	"\rroute_changed\x18\x03 \x01(\v2\x1c.quakemesh.wire.RouteChangedH\x00R\frouteChanged\x12]\n" +
	"\x17dtn_queue_depth_changed\x18\x04 \x01(\v2$.quakemesh.wire.DtnQueueDepthChangedH\x00R\x14dtnQueueDepthChanged\x12P\n" +
	"\x12hub_status_changed\x18\x05 \x01(\v2 .quakemesh.wire.HubStatusChangedH\x00R\x10hubStatusChanged\x12e\n" +
	"\x19internet_fallback_changed\x18\x06 \x01(\v2'.quakemesh.wire.InternetFallbackChangedH\x00R\x17internetFallbackChangedB\a\n" +
	"\x05event\"A\n" +
	"\x10HubStatusChanged\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\fR\x05hubId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"D\n" +
	"\x11NodeStatusChanged\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x84\x01\n" +
	"\fRouteChanged\x12\x1e\n" +
	"\vdst_node_id\x18\x01 \x01(\fR\tdstNodeId\x12'\n" +
	"\x10next_hop_node_id\x18\x02 \x01(\fR\rnextHopNodeId\x12\x0e\n" +
	"\x02tq\x18\x03 \x01(\x01R\x02tq\x12\x1b\n" +
	"\thop_count\x18\x04 \x01(\rR\bhopCount\",\n" +
	"\x14DtnQueueDepthChanged\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\rR\x05depth\"3\n" +
	"\x17InternetFallbackChanged\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabledBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_management_proto_rawDescOnce sync.Once
	file_management_proto_rawDescData []byte
)

func file_management_proto_rawDescGZIP() []byte {
	file_management_proto_rawDescOnce.Do(func() {
		file_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)))
	})
	return file_management_proto_rawDescData
}

var file_management_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_management_proto_goTypes = []any{
	(*ManagementEvent)(nil),         // 0: quakemesh.wire.ManagementEvent
	(*HubStatusChanged)(nil),        // 1: quakemesh.wire.HubStatusChanged
	(*NodeStatusChanged)(nil),       // 2: quakemesh.wire.NodeStatusChanged
	(*RouteChanged)(nil),            // 3: quakemesh.wire.RouteChanged
	(*DtnQueueDepthChanged)(nil),    // 4: quakemesh.wire.DtnQueueDepthChanged
	(*InternetFallbackChanged)(nil), // 5: quakemesh.wire.InternetFallbackChanged
}
var file_management_proto_depIdxs = []int32{
	2, // 0: quakemesh.wire.ManagementEvent.node_status_changed:type_name -> quakemesh.wire.NodeStatusChanged
	3, // 1: quakemesh.wire.ManagementEvent.route_changed:type_name -> quakemesh.wire.RouteChanged
	4, // 2: quakemesh.wire.ManagementEvent.dtn_queue_depth_changed:type_name -> quakemesh.wire.DtnQueueDepthChanged
	1, // 3: quakemesh.wire.ManagementEvent.hub_status_changed:type_name -> quakemesh.wire.HubStatusChanged
	5, // 4: quakemesh.wire.ManagementEvent.internet_fallback_changed:type_name -> quakemesh.wire.InternetFallbackChanged
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_management_proto_init() }
func file_management_proto_init() {
	if File_management_proto != nil {
		return
	}
	file_management_proto_msgTypes[0].OneofWrappers = []any{
		(*ManagementEvent_NodeStatusChanged)(nil),
		(*ManagementEvent_RouteChanged)(nil),
		(*ManagementEvent_DtnQueueDepthChanged)(nil),
		(*ManagementEvent_HubStatusChanged)(nil),
		(*ManagementEvent_InternetFallbackChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_proto_goTypes,
		DependencyIndexes: file_management_proto_depIdxs,
		MessageInfos:      file_management_proto_msgTypes,
	}.Build()
	File_management_proto = out.File
	file_management_proto_goTypes = nil
	file_management_proto_depIdxs = nil
}
