// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: management.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Emitted when an app publishes to the SOS topic via the mesh-sdk daemon.
type SosAlertPublished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SosAlertPublished) Reset() {
	*x = SosAlertPublished{}
	mi := &file_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SosAlertPublished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SosAlertPublished) ProtoMessage() {}

func (x *SosAlertPublished) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SosAlertPublished.ProtoReflect.Descriptor instead.
func (*SosAlertPublished) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

func (x *SosAlertPublished) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *SosAlertPublished) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SosAlertPublished) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SosAlertPublished) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

// Live event stream from a Hub's loopback management API (127.0.0.1:8083)
// to QuakeMeshMonitor, delivered over the Monitor's /ws WebSocket endpoint.
type ManagementEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EmittedAtUnixMs int64                  `protobuf:"varint,1,opt,name=emitted_at_unix_ms,json=emittedAtUnixMs,proto3" json:"emitted_at_unix_ms,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ManagementEvent_NodeStatusChanged
	//	*ManagementEvent_RouteChanged
	//	*ManagementEvent_DtnQueueDepthChanged
	//	*ManagementEvent_HubStatusChanged
	//	*ManagementEvent_InternetFallbackChanged
	//	*ManagementEvent_AppPresenceChanged
	//	*ManagementEvent_BanProposalChanged
	//	*ManagementEvent_BanVerdictChanged
	//	*ManagementEvent_SosAlertPublished
	Event         isManagementEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagementEvent) Reset() {
	*x = ManagementEvent{}
	mi := &file_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementEvent) ProtoMessage() {}

func (x *ManagementEvent) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementEvent.ProtoReflect.Descriptor instead.
func (*ManagementEvent) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{1}
}

func (x *ManagementEvent) GetEmittedAtUnixMs() int64 {
	if x != nil {
		return x.EmittedAtUnixMs
	}
	return 0
}

func (x *ManagementEvent) GetEvent() isManagementEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ManagementEvent) GetNodeStatusChanged() *NodeStatusChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_NodeStatusChanged); ok {
			return x.NodeStatusChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetRouteChanged() *RouteChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_RouteChanged); ok {
			return x.RouteChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetDtnQueueDepthChanged() *DtnQueueDepthChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_DtnQueueDepthChanged); ok {
			return x.DtnQueueDepthChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetHubStatusChanged() *HubStatusChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_HubStatusChanged); ok {
			return x.HubStatusChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetInternetFallbackChanged() *InternetFallbackChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_InternetFallbackChanged); ok {
			return x.InternetFallbackChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetAppPresenceChanged() *AppPresenceChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_AppPresenceChanged); ok {
			return x.AppPresenceChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetBanProposalChanged() *BanProposalChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_BanProposalChanged); ok {
			return x.BanProposalChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetBanVerdictChanged() *BanVerdictChanged {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_BanVerdictChanged); ok {
			return x.BanVerdictChanged
		}
	}
	return nil
}

func (x *ManagementEvent) GetSosAlertPublished() *SosAlertPublished {
	if x != nil {
		if x, ok := x.Event.(*ManagementEvent_SosAlertPublished); ok {
			return x.SosAlertPublished
		}
	}
	return nil
}

type isManagementEvent_Event interface {
	isManagementEvent_Event()
}

type ManagementEvent_NodeStatusChanged struct {
	NodeStatusChanged *NodeStatusChanged `protobuf:"bytes,2,opt,name=node_status_changed,json=nodeStatusChanged,proto3,oneof"`
}

type ManagementEvent_RouteChanged struct {
	RouteChanged *RouteChanged `protobuf:"bytes,3,opt,name=route_changed,json=routeChanged,proto3,oneof"`
}

type ManagementEvent_DtnQueueDepthChanged struct {
	DtnQueueDepthChanged *DtnQueueDepthChanged `protobuf:"bytes,4,opt,name=dtn_queue_depth_changed,json=dtnQueueDepthChanged,proto3,oneof"`
}

type ManagementEvent_HubStatusChanged struct {
	HubStatusChanged *HubStatusChanged `protobuf:"bytes,5,opt,name=hub_status_changed,json=hubStatusChanged,proto3,oneof"`
}

type ManagementEvent_InternetFallbackChanged struct {
	InternetFallbackChanged *InternetFallbackChanged `protobuf:"bytes,6,opt,name=internet_fallback_changed,json=internetFallbackChanged,proto3,oneof"`
}

type ManagementEvent_AppPresenceChanged struct {
	AppPresenceChanged *AppPresenceChanged `protobuf:"bytes,7,opt,name=app_presence_changed,json=appPresenceChanged,proto3,oneof"`
}

type ManagementEvent_BanProposalChanged struct {
	BanProposalChanged *BanProposalChanged `protobuf:"bytes,8,opt,name=ban_proposal_changed,json=banProposalChanged,proto3,oneof"`
}

type ManagementEvent_BanVerdictChanged struct {
	BanVerdictChanged *BanVerdictChanged `protobuf:"bytes,9,opt,name=ban_verdict_changed,json=banVerdictChanged,proto3,oneof"`
}

type ManagementEvent_SosAlertPublished struct {
	SosAlertPublished *SosAlertPublished `protobuf:"bytes,10,opt,name=sos_alert_published,json=sosAlertPublished,proto3,oneof"`
}

func (*ManagementEvent_NodeStatusChanged) isManagementEvent_Event() {}

func (*ManagementEvent_RouteChanged) isManagementEvent_Event() {}

func (*ManagementEvent_DtnQueueDepthChanged) isManagementEvent_Event() {}

func (*ManagementEvent_HubStatusChanged) isManagementEvent_Event() {}

func (*ManagementEvent_InternetFallbackChanged) isManagementEvent_Event() {}

func (*ManagementEvent_AppPresenceChanged) isManagementEvent_Event() {}

func (*ManagementEvent_BanProposalChanged) isManagementEvent_Event() {}

func (*ManagementEvent_BanVerdictChanged) isManagementEvent_Event() {}

func (*ManagementEvent_SosAlertPublished) isManagementEvent_Event() {}

type HubStatusChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HubId         []byte                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubStatusChanged) Reset() {
	*x = HubStatusChanged{}
	mi := &file_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubStatusChanged) ProtoMessage() {}

func (x *HubStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubStatusChanged.ProtoReflect.Descriptor instead.
func (*HubStatusChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{2}
}

func (x *HubStatusChanged) GetHubId() []byte {
	if x != nil {
		return x.HubId
	}
	return nil
}

func (x *HubStatusChanged) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NodeStatusChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusChanged) Reset() {
	*x = NodeStatusChanged{}
	mi := &file_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusChanged) ProtoMessage() {}

func (x *NodeStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusChanged.ProtoReflect.Descriptor instead.
func (*NodeStatusChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatusChanged) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *NodeStatusChanged) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RouteChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstNodeId     []byte                 `protobuf:"bytes,1,opt,name=dst_node_id,json=dstNodeId,proto3" json:"dst_node_id,omitempty"`
	NextHopNodeId []byte                 `protobuf:"bytes,2,opt,name=next_hop_node_id,json=nextHopNodeId,proto3" json:"next_hop_node_id,omitempty"`
	Tq            float64                `protobuf:"fixed64,3,opt,name=tq,proto3" json:"tq,omitempty"`
	HopCount      uint32                 `protobuf:"varint,4,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteChanged) Reset() {
	*x = RouteChanged{}
	mi := &file_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteChanged) ProtoMessage() {}

func (x *RouteChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteChanged.ProtoReflect.Descriptor instead.
func (*RouteChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{4}
}

func (x *RouteChanged) GetDstNodeId() []byte {
	if x != nil {
		return x.DstNodeId
	}
	return nil
}

func (x *RouteChanged) GetNextHopNodeId() []byte {
	if x != nil {
		return x.NextHopNodeId
	}
	return nil
}

func (x *RouteChanged) GetTq() float64 {
	if x != nil {
		return x.Tq
	}
	return 0
}

func (x *RouteChanged) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

type DtnQueueDepthChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depth         uint32                 `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtnQueueDepthChanged) Reset() {
	*x = DtnQueueDepthChanged{}
	mi := &file_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtnQueueDepthChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtnQueueDepthChanged) ProtoMessage() {}

func (x *DtnQueueDepthChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtnQueueDepthChanged.ProtoReflect.Descriptor instead.
func (*DtnQueueDepthChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{5}
}

func (x *DtnQueueDepthChanged) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type InternetFallbackChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternetFallbackChanged) Reset() {
	*x = InternetFallbackChanged{}
	mi := &file_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternetFallbackChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternetFallbackChanged) ProtoMessage() {}

func (x *InternetFallbackChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternetFallbackChanged.ProtoReflect.Descriptor instead.
func (*InternetFallbackChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{6}
}

func (x *InternetFallbackChanged) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AppPresenceChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppPresenceChanged) Reset() {
	*x = AppPresenceChanged{}
	mi := &file_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppPresenceChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPresenceChanged) ProtoMessage() {}

func (x *AppPresenceChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPresenceChanged.ProtoReflect.Descriptor instead.
func (*AppPresenceChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{7}
}

func (x *AppPresenceChanged) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *AppPresenceChanged) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppPresenceChanged) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type BanProposalChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BanId         []byte                 `protobuf:"bytes,1,opt,name=ban_id,json=banId,proto3" json:"ban_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionRange  string                 `protobuf:"bytes,3,opt,name=version_range,json=versionRange,proto3" json:"version_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanProposalChanged) Reset() {
	*x = BanProposalChanged{}
	mi := &file_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanProposalChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanProposalChanged) ProtoMessage() {}

func (x *BanProposalChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanProposalChanged.ProtoReflect.Descriptor instead.
func (*BanProposalChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{8}
}

func (x *BanProposalChanged) GetBanId() []byte {
	if x != nil {
		return x.BanId
	}
	return nil
}

func (x *BanProposalChanged) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BanProposalChanged) GetVersionRange() string {
	if x != nil {
		return x.VersionRange
	}
	return ""
}

type BanVerdictChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BanId         []byte                 `protobuf:"bytes,1,opt,name=ban_id,json=banId,proto3" json:"ban_id,omitempty"`
	HubId         []byte                 `protobuf:"bytes,2,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Agree         bool                   `protobuf:"varint,3,opt,name=agree,proto3" json:"agree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanVerdictChanged) Reset() {
	*x = BanVerdictChanged{}
	mi := &file_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanVerdictChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanVerdictChanged) ProtoMessage() {}

func (x *BanVerdictChanged) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanVerdictChanged.ProtoReflect.Descriptor instead.
func (*BanVerdictChanged) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{9}
}

func (x *BanVerdictChanged) GetBanId() []byte {
	if x != nil {
		return x.BanId
	}
	return nil
}

func (x *BanVerdictChanged) GetHubId() []byte {
	if x != nil {
		return x.HubId
	}
	return nil
}

func (x *BanVerdictChanged) GetAgree() bool {
	if x != nil {
		return x.Agree
	}
	return false
}

var File_management_proto protoreflect.FileDescriptor

const file_management_proto_rawDesc = "" +
	"\n" +
	"\x10management.proto\x12\x0equakemesh.wire\"|\n" +
	"\x11SosAlertPublished\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\fR\vpayloadJson\"\xd3\x06\n" +
	"\x0fManagementEvent\x12+\n" +
	"\x12emitted_at_unix_ms\x18\x01 \x01(\x03R\x0femittedAtUnixMs\x12S\n" +
	"\x13node_status_changed\x18\x02 \x01(\v2!.quakemesh.wire.NodeStatusChangedH\x00R\x11nodeStatusChanged\x12C\n" +
	"\rroute_changed\x18\x03 \x01(\v2\x1c.quakemesh.wire.RouteChangedH\x00R\frouteChanged\x12]\n" +
	"\x17dtn_queue_depth_changed\x18\x04 \x01(\v2$.quakemesh.wire.DtnQueueDepthChangedH\x00R\x14dtnQueueDepthChanged\x12P\n" +
	"\x12hub_status_changed\x18\x05 \x01(\v2 .quakemesh.wire.HubStatusChangedH\x00R\x10hubStatusChanged\x12e\n" +
	"\x19internet_fallback_changed\x18\x06 \x01(\v2'.quakemesh.wire.InternetFallbackChangedH\x00R\x17internetFallbackChanged\x12V\n" +
	"\x14app_presence_changed\x18\a \x01(\v2\".quakemesh.wire.AppPresenceChangedH\x00R\x12appPresenceChanged\x12V\n" +
	"\x14ban_proposal_changed\x18\b \x01(\v2\".quakemesh.wire.BanProposalChangedH\x00R\x12banProposalChanged\x12S\n" +
	"\x13ban_verdict_changed\x18\t \x01(\v2!.quakemesh.wire.BanVerdictChangedH\x00R\x11banVerdictChanged\x12S\n" +
	"\x13sos_alert_published\x18\n" +
	" \x01(\v2!.quakemesh.wire.SosAlertPublishedH\x00R\x11sosAlertPublishedB\a\n" +
	"\x05event\"A\n" +
	"\x10HubStatusChanged\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\fR\x05hubId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"D\n" +
	"\x11NodeStatusChanged\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x84\x01\n" +
	"\fRouteChanged\x12\x1e\n" +
	"\vdst_node_id\x18\x01 \x01(\fR\tdstNodeId\x12'\n" +
	"\x10next_hop_node_id\x18\x02 \x01(\fR\rnextHopNodeId\x12\x0e\n" +
	"\x02tq\x18\x03 \x01(\x01R\x02tq\x12\x1b\n" +
	"\thop_count\x18\x04 \x01(\rR\bhopCount\",\n" +
	"\x14DtnQueueDepthChanged\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\rR\x05depth\"3\n" +
	"\x17InternetFallbackChanged\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"e\n" +
	"\x12AppPresenceChanged\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\"g\n" +
	"\x12BanProposalChanged\x12\x15\n" +
	"\x06ban_id\x18\x01 \x01(\fR\x05banId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12#\n" +
	"\rversion_range\x18\x03 \x01(\tR\fversionRange\"W\n" +
	"\x11BanVerdictChanged\x12\x15\n" +
	"\x06ban_id\x18\x01 \x01(\fR\x05banId\x12\x15\n" +
	"\x06hub_id\x18\x02 \x01(\fR\x05hubId\x12\x14\n" +
	"\x05agree\x18\x03 \x01(\bR\x05agreeBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_management_proto_rawDescOnce sync.Once
	file_management_proto_rawDescData []byte
)

func file_management_proto_rawDescGZIP() []byte {
	file_management_proto_rawDescOnce.Do(func() {
		file_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)))
	})
	return file_management_proto_rawDescData
}

var file_management_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_management_proto_goTypes = []any{
	(*SosAlertPublished)(nil),       // 0: quakemesh.wire.SosAlertPublished
	(*ManagementEvent)(nil),         // 1: quakemesh.wire.ManagementEvent
	(*HubStatusChanged)(nil),        // 2: quakemesh.wire.HubStatusChanged
	(*NodeStatusChanged)(nil),       // 3: quakemesh.wire.NodeStatusChanged
	(*RouteChanged)(nil),            // 4: quakemesh.wire.RouteChanged
	(*DtnQueueDepthChanged)(nil),    // 5: quakemesh.wire.DtnQueueDepthChanged
	(*InternetFallbackChanged)(nil), // 6: quakemesh.wire.InternetFallbackChanged
	(*AppPresenceChanged)(nil),      // 7: quakemesh.wire.AppPresenceChanged
	(*BanProposalChanged)(nil),      // 8: quakemesh.wire.BanProposalChanged
	(*BanVerdictChanged)(nil),       // 9: quakemesh.wire.BanVerdictChanged
}
var file_management_proto_depIdxs = []int32{
	3, // 0: quakemesh.wire.ManagementEvent.node_status_changed:type_name -> quakemesh.wire.NodeStatusChanged
	4, // 1: quakemesh.wire.ManagementEvent.route_changed:type_name -> quakemesh.wire.RouteChanged
	5, // 2: quakemesh.wire.ManagementEvent.dtn_queue_depth_changed:type_name -> quakemesh.wire.DtnQueueDepthChanged
	2, // 3: quakemesh.wire.ManagementEvent.hub_status_changed:type_name -> quakemesh.wire.HubStatusChanged
	6, // 4: quakemesh.wire.ManagementEvent.internet_fallback_changed:type_name -> quakemesh.wire.InternetFallbackChanged
	7, // 5: quakemesh.wire.ManagementEvent.app_presence_changed:type_name -> quakemesh.wire.AppPresenceChanged
	8, // 6: quakemesh.wire.ManagementEvent.ban_proposal_changed:type_name -> quakemesh.wire.BanProposalChanged
	9, // 7: quakemesh.wire.ManagementEvent.ban_verdict_changed:type_name -> quakemesh.wire.BanVerdictChanged
	0, // 8: quakemesh.wire.ManagementEvent.sos_alert_published:type_name -> quakemesh.wire.SosAlertPublished
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_management_proto_init() }
func file_management_proto_init() {
	if File_management_proto != nil {
		return
	}
	file_management_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagementEvent_NodeStatusChanged)(nil),
		(*ManagementEvent_RouteChanged)(nil),
		(*ManagementEvent_DtnQueueDepthChanged)(nil),
		(*ManagementEvent_HubStatusChanged)(nil),
		(*ManagementEvent_InternetFallbackChanged)(nil),
		(*ManagementEvent_AppPresenceChanged)(nil),
		(*ManagementEvent_BanProposalChanged)(nil),
		(*ManagementEvent_BanVerdictChanged)(nil),
		(*ManagementEvent_SosAlertPublished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_proto_goTypes,
		DependencyIndexes: file_management_proto_depIdxs,
		MessageInfos:      file_management_proto_msgTypes,
	}.Build()
	File_management_proto = out.File
	file_management_proto_goTypes = nil
	file_management_proto_depIdxs = nil
}
