// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.
//   0.0.6 - Phase 5: OGM last_hop_id and hop_count for multi-hop rebroadcast.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ogm.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Originator Message: BATMAN-adv-inspired routing advertisement.
type Ogm struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SequenceNumber    uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Ttl               uint32                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	IsStartupAnnounce bool                   `protobuf:"varint,4,opt,name=is_startup_announce,json=isStartupAnnounce,proto3" json:"is_startup_announce,omitempty"` // high-priority "I'm up" variant
	LastHopId         []byte                 `protobuf:"bytes,5,opt,name=last_hop_id,json=lastHopId,proto3" json:"last_hop_id,omitempty"`                          // rebroadcaster NodeID (empty at origin)
	HopCount          uint32                 `protobuf:"varint,6,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`                              // hops from originator (0 at origin)
	Lat               *float64               `protobuf:"fixed64,7,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon               *float64               `protobuf:"fixed64,8,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	LocationAccuracyM *float32               `protobuf:"fixed32,9,opt,name=location_accuracy_m,json=locationAccuracyM,proto3,oneof" json:"location_accuracy_m,omitempty"`
	LocationAtUnixMs  *int64                 `protobuf:"varint,10,opt,name=location_at_unix_ms,json=locationAtUnixMs,proto3,oneof" json:"location_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Ogm) Reset() {
	*x = Ogm{}
	mi := &file_ogm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ogm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ogm) ProtoMessage() {}

func (x *Ogm) ProtoReflect() protoreflect.Message {
	mi := &file_ogm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ogm.ProtoReflect.Descriptor instead.
func (*Ogm) Descriptor() ([]byte, []int) {
	return file_ogm_proto_rawDescGZIP(), []int{0}
}

func (x *Ogm) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Ogm) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Ogm) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Ogm) GetIsStartupAnnounce() bool {
	if x != nil {
		return x.IsStartupAnnounce
	}
	return false
}

func (x *Ogm) GetLastHopId() []byte {
	if x != nil {
		return x.LastHopId
	}
	return nil
}

func (x *Ogm) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *Ogm) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Ogm) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *Ogm) GetLocationAccuracyM() float32 {
	if x != nil && x.LocationAccuracyM != nil {
		return *x.LocationAccuracyM
	}
	return 0
}

func (x *Ogm) GetLocationAtUnixMs() int64 {
	if x != nil && x.LocationAtUnixMs != nil {
		return *x.LocationAtUnixMs
	}
	return 0
}

// Direct-neighbour liveness ping, independent of OGM refresh cadence.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SentAtUnixMs  int64                  `protobuf:"varint,2,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_ogm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_ogm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_ogm_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Hello) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

var File_ogm_proto protoreflect.FileDescriptor

const file_ogm_proto_rawDesc = "" +
	"\n" +
	"\togm.proto\x12\x0equakemesh.wire\"\x9d\x03\n" +
	"\x03Ogm\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x12.\n" +
	"\x13is_startup_announce\x18\x04 \x01(\bR\x11isStartupAnnounce\x12\x1e\n" +
	"\vlast_hop_id\x18\x05 \x01(\fR\tlastHopId\x12\x1b\n" +
	"\thop_count\x18\x06 \x01(\rR\bhopCount\x12\x15\n" +
	"\x03lat\x18\a \x01(\x01H\x00R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\b \x01(\x01H\x01R\x03lon\x88\x01\x01\x123\n" +
	"\x13location_accuracy_m\x18\t \x01(\x02H\x02R\x11locationAccuracyM\x88\x01\x01\x122\n" +
	"\x13location_at_unix_ms\x18\n" +
	" \x01(\x03H\x03R\x10locationAtUnixMs\x88\x01\x01B\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lonB\x16\n" +
	"\x14_location_accuracy_mB\x16\n" +
	"\x14_location_at_unix_ms\"G\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x02 \x01(\x03R\fsentAtUnixMsBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_ogm_proto_rawDescOnce sync.Once
	file_ogm_proto_rawDescData []byte
)

func file_ogm_proto_rawDescGZIP() []byte {
	file_ogm_proto_rawDescOnce.Do(func() {
		file_ogm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ogm_proto_rawDesc), len(file_ogm_proto_rawDesc)))
	})
	return file_ogm_proto_rawDescData
}

var file_ogm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ogm_proto_goTypes = []any{
	(*Ogm)(nil),   // 0: quakemesh.wire.Ogm
	(*Hello)(nil), // 1: quakemesh.wire.Hello
}
var file_ogm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ogm_proto_init() }
func file_ogm_proto_init() {
	if File_ogm_proto != nil {
		return
	}
	file_ogm_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ogm_proto_rawDesc), len(file_ogm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ogm_proto_goTypes,
		DependencyIndexes: file_ogm_proto_depIdxs,
		MessageInfos:      file_ogm_proto_msgTypes,
	}.Build()
	File_ogm_proto = out.File
	file_ogm_proto_goTypes = nil
	file_ogm_proto_depIdxs = nil
}
