// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: relay_hub.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A hub advertised as relay-capable (publicly reachable + relaying opt-in).
type RelayHubRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HubId              []byte                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Ip                 string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port               uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Source             string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // "manual" | "gossip" | "client"
	LastVerifiedUnixMs int64                  `protobuf:"varint,5,opt,name=last_verified_unix_ms,json=lastVerifiedUnixMs,proto3" json:"last_verified_unix_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelayHubRecord) Reset() {
	*x = RelayHubRecord{}
	mi := &file_relay_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayHubRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayHubRecord) ProtoMessage() {}

func (x *RelayHubRecord) ProtoReflect() protoreflect.Message {
	mi := &file_relay_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayHubRecord.ProtoReflect.Descriptor instead.
func (*RelayHubRecord) Descriptor() ([]byte, []int) {
	return file_relay_hub_proto_rawDescGZIP(), []int{0}
}

func (x *RelayHubRecord) GetHubId() []byte {
	if x != nil {
		return x.HubId
	}
	return nil
}

func (x *RelayHubRecord) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RelayHubRecord) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RelayHubRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RelayHubRecord) GetLastVerifiedUnixMs() int64 {
	if x != nil {
		return x.LastVerifiedUnixMs
	}
	return 0
}

var File_relay_hub_proto protoreflect.FileDescriptor

const file_relay_hub_proto_rawDesc = "" +
	"\n" +
	"\x0frelay_hub.proto\x12\x0equakemesh.wire\"\x96\x01\n" +
	"\x0eRelayHubRecord\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\fR\x05hubId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x121\n" +
	"\x15last_verified_unix_ms\x18\x05 \x01(\x03R\x12lastVerifiedUnixMsBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_relay_hub_proto_rawDescOnce sync.Once
	file_relay_hub_proto_rawDescData []byte
)

func file_relay_hub_proto_rawDescGZIP() []byte {
	file_relay_hub_proto_rawDescOnce.Do(func() {
		file_relay_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_hub_proto_rawDesc), len(file_relay_hub_proto_rawDesc)))
	})
	return file_relay_hub_proto_rawDescData
}

var file_relay_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_relay_hub_proto_goTypes = []any{
	(*RelayHubRecord)(nil), // 0: quakemesh.wire.RelayHubRecord
}
var file_relay_hub_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relay_hub_proto_init() }
func file_relay_hub_proto_init() {
	if File_relay_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_hub_proto_rawDesc), len(file_relay_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_hub_proto_goTypes,
		DependencyIndexes: file_relay_hub_proto_depIdxs,
		MessageInfos:      file_relay_hub_proto_msgTypes,
	}.Build()
	File_relay_hub_proto = out.File
	file_relay_hub_proto_goTypes = nil
	file_relay_hub_proto_depIdxs = nil
}
