// Copyright (c) 2026 John Dovey <dovey.john@gmail.com>
//
// Changelog:
//   0.0.1 - Initial scaffold.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: trust.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Observed direct radio contact between two nodes. Not self-reported by
// the observed node -- recorded by the observer, so it cannot be forged.
type ProximityEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObserverNodeId   []byte                 `protobuf:"bytes,1,opt,name=observer_node_id,json=observerNodeId,proto3" json:"observer_node_id,omitempty"`
	ObservedNodeId   []byte                 `protobuf:"bytes,2,opt,name=observed_node_id,json=observedNodeId,proto3" json:"observed_node_id,omitempty"`
	Rssi             int32                  `protobuf:"varint,3,opt,name=rssi,proto3" json:"rssi,omitempty"`
	Transport        string                 `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	ObservedAtUnixMs int64                  `protobuf:"varint,5,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProximityEvent) Reset() {
	*x = ProximityEvent{}
	mi := &file_trust_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProximityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProximityEvent) ProtoMessage() {}

func (x *ProximityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_trust_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProximityEvent.ProtoReflect.Descriptor instead.
func (*ProximityEvent) Descriptor() ([]byte, []int) {
	return file_trust_proto_rawDescGZIP(), []int{0}
}

func (x *ProximityEvent) GetObserverNodeId() []byte {
	if x != nil {
		return x.ObserverNodeId
	}
	return nil
}

func (x *ProximityEvent) GetObservedNodeId() []byte {
	if x != nil {
		return x.ObservedNodeId
	}
	return nil
}

func (x *ProximityEvent) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *ProximityEvent) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ProximityEvent) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

// Signed explicit trust endorsement. Can only be issued for a node_id the
// endorsing device has itself recorded a ProximityEvent with.
type TrustEndorsement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EndorserNodeId   []byte                 `protobuf:"bytes,1,opt,name=endorser_node_id,json=endorserNodeId,proto3" json:"endorser_node_id,omitempty"`
	EndorsedNodeId   []byte                 `protobuf:"bytes,2,opt,name=endorsed_node_id,json=endorsedNodeId,proto3" json:"endorsed_node_id,omitempty"`
	EndorsedAtUnixMs int64                  `protobuf:"varint,3,opt,name=endorsed_at_unix_ms,json=endorsedAtUnixMs,proto3" json:"endorsed_at_unix_ms,omitempty"`
	Signature        []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrustEndorsement) Reset() {
	*x = TrustEndorsement{}
	mi := &file_trust_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustEndorsement) ProtoMessage() {}

func (x *TrustEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_trust_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustEndorsement.ProtoReflect.Descriptor instead.
func (*TrustEndorsement) Descriptor() ([]byte, []int) {
	return file_trust_proto_rawDescGZIP(), []int{1}
}

func (x *TrustEndorsement) GetEndorserNodeId() []byte {
	if x != nil {
		return x.EndorserNodeId
	}
	return nil
}

func (x *TrustEndorsement) GetEndorsedNodeId() []byte {
	if x != nil {
		return x.EndorsedNodeId
	}
	return nil
}

func (x *TrustEndorsement) GetEndorsedAtUnixMs() int64 {
	if x != nil {
		return x.EndorsedAtUnixMs
	}
	return 0
}

func (x *TrustEndorsement) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_trust_proto protoreflect.FileDescriptor

const file_trust_proto_rawDesc = "" +
	"\n" +
	"\vtrust.proto\x12\x0equakemesh.wire\"\xc5\x01\n" +
	"\x0eProximityEvent\x12(\n" +
	"\x10observer_node_id\x18\x01 \x01(\fR\x0eobserverNodeId\x12(\n" +
	"\x10observed_node_id\x18\x02 \x01(\fR\x0eobservedNodeId\x12\x12\n" +
	"\x04rssi\x18\x03 \x01(\x05R\x04rssi\x12\x1c\n" +
	"\ttransport\x18\x04 \x01(\tR\ttransport\x12-\n" +
	"\x13observed_at_unix_ms\x18\x05 \x01(\x03R\x10observedAtUnixMs\"\xb3\x01\n" +
	"\x10TrustEndorsement\x12(\n" +
	"\x10endorser_node_id\x18\x01 \x01(\fR\x0eendorserNodeId\x12(\n" +
	"\x10endorsed_node_id\x18\x02 \x01(\fR\x0eendorsedNodeId\x12-\n" +
	"\x13endorsed_at_unix_ms\x18\x03 \x01(\x03R\x10endorsedAtUnixMs\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignatureBE\n" +
	"\x13net.quakemesh.protoZ.github.com/JohnDovey/QuakeMesh/proto/wire;wireb\x06proto3"

var (
	file_trust_proto_rawDescOnce sync.Once
	file_trust_proto_rawDescData []byte
)

func file_trust_proto_rawDescGZIP() []byte {
	file_trust_proto_rawDescOnce.Do(func() {
		file_trust_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trust_proto_rawDesc), len(file_trust_proto_rawDesc)))
	})
	return file_trust_proto_rawDescData
}

var file_trust_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trust_proto_goTypes = []any{
	(*ProximityEvent)(nil),   // 0: quakemesh.wire.ProximityEvent
	(*TrustEndorsement)(nil), // 1: quakemesh.wire.TrustEndorsement
}
var file_trust_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trust_proto_init() }
func file_trust_proto_init() {
	if File_trust_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trust_proto_rawDesc), len(file_trust_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trust_proto_goTypes,
		DependencyIndexes: file_trust_proto_depIdxs,
		MessageInfos:      file_trust_proto_msgTypes,
	}.Build()
	File_trust_proto = out.File
	file_trust_proto_goTypes = nil
	file_trust_proto_depIdxs = nil
}
